language: python
python:
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8
      dist: xenial
      sudo: true
install:
  - curl -Lo $HOME/bin/ytt https://github.com/k14s/ytt/releases/download/v0.26.0/ytt-linux-amd64 && chmod +x $HOME/bin/ytt
  - pip install -r requirements-dev.txt --upgrade
  - pip install coveralls
script:
  - pylint ddb
  - coverage run --source=ddb -m pytest
  - python setup.py build
after_success:
  - coveralls