site_name: Docker Devbox - ddb

site_url: https://gfi-centre-ouest.github.io/docker-devbox-ddb
site_description: Erase environment differences, make developers happy !
site_author: Rémi Alvergnat <remi.alvergnat@gfi.world>, Pierre Lejeune <pierre.lejeune@gfi.world>
copyright: GFI Informatique

repo_url: https://github.com/gfi-centre-ouest/docker-devbox-ddb

theme:
  language: 'en'
  name: 'material'

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Guides:
      - Foreword: guides/foreword.md
      - PostgreSQL, Symfony, VueJS:  guides/psql-symfony-vue.md
  - References:
      - Foreword: references/foreword.md
      - Features:
        - Git: references/features/git.md
        - Gitignore: references/features/gitignore.md
        - Jsonnet: references/features/jsonnet.md
        - SmartCD: references/features/smartcd.md

plugins:
  - search

dev_addr: 0.0.0.0:8000
