site_name: Docker Devbox - ddb

site_url: https://gfi-centre-ouest.github.io/docker-devbox-ddb
site_description: Erase environment differences, make developers happy !
site_author: Rémi Alvergnat <remi.alvergnat@gfi.world>, Pierre Lejeune <pierre.lejeune@gfi.world>
copyright: GFI Informatique

repo_url: https://github.com/gfi-centre-ouest/docker-devbox-ddb

theme:
  language: 'en'
  name: 'material'

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Overview: overview.md
  - Configuration: configuration.md
  - Commands: commands.md
  - Guides:
      - PostgreSQL, Symfony, VueJS:  guides/psql-symfony-vue.md
  - Features:
    - docker: features/docker.md
    - fixuid: features/fixuid.md
    - git: features/git.md
    - gitignore: features/gitignore.md
    - jsonnet: features/jsonnet.md
    - shell: features/shell.md
    - smartCD: features/smartcd.md

plugins:
  - search

dev_addr: 0.0.0.0:8000
