name: release
on:
  push:
    branches: [ master ]
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]
    steps:
      # Setup docker
      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: "19.03"
          docker_channel: "stable"

      # Setup docker
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v2

      - name: "Git User config"
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"

      - name: "Install Dependencies"
        run: pip install -r requirements-dev.txt

      - name: "Publish release"
        run: semantic-release publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

      - name: "Merger master to develop"
        uses: robotology/gh-action-nightly-merge@v1.3.1
        with:
          stable_branch: 'master'
          development_branch: 'devel'
          allow_ff: true
          user_name: github-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
